rename comb-to-cggi to secret-to-cggi
google/heir pull request #1058
Opened 2024-10-17 12:56 UTC by ahmedshakill

implements #1041

2024-10-17 15:58 UTC, asraa reviewed
Thank you so much for taking care of this! Just a quick nit on the namespace but it looks great to me.

The CMakeList probably needs updating anyway after merging.. @AlexanderViand-Intel  D:

2024-10-17 15:58 UTC, asraa commented on docs/content/en/docs/getting_started.md
>    $PWD/tests/comb_to_cggi/add_one.mlir
Thanks for finding the documentation reference! If you can this test directory also needs to be updated:
```suggestion
  $PWD/tests/Dialect/Secret/Conversions/secret_to_cggi/add_one.mlir
```

2024-10-17 15:58 UTC, asraa commented on lib/Dialect/Secret/Conversions/SecretToCGGI/SecretToCGGI.cpp
> +}  // namespace mlir::heir::secret
the namespace on line 42 is still `comb` - the other SecretToScheme are just `mlir::heir` - so maybe we can keep that convention for consistency?

2024-10-17 15:58 UTC, asraa commented on lib/Dialect/Secret/Conversions/SecretToCGGI/SecretToCGGI.h
> +namespace mlir::heir::comb {
same with the namespace here - maybe just mlir::heir

2024-10-17 18:00 UTC, AlexanderViand-Intel commented
> The CMakeList probably needs updating anyway after merging.. @AlexanderViand-Intel D:

Yep, I'll deal with rebasing `cmake` onto this once this is merged 👍

2024-10-17 22:13 UTC, AlexanderViand-Intel requested changes

2024-10-17 22:13 UTC, AlexanderViand-Intel commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
Actually, since it looks like #1035 unexpectedly got merged already, we'll have to fix the CMakeLists.txt in this PR after all.

2024-10-17 22:13 UTC, AlexanderViand-Intel commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
> +add_public_tablegen_target(MLIRSecretTransformsIncGen)
```suggestion
add_heir_pass(SecretToCGGI)
```

2024-10-17 22:13 UTC, AlexanderViand-Intel commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
> +add_mlir_dialect_library(MLIRSecretTransforms
```suggestion
add_mlir_dialect_library(HEIRSecretToCGGI
```

2024-10-17 22:13 UTC, AlexanderViand-Intel commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
> +    MLIRSecretTransformsIncGen
```suggestion
    HEIRSecretToCGGIIncGen
```

2024-10-18 03:53 UTC, ahmedshakill commented
rebased on upstream and squashed commits

2024-10-18 14:22 UTC, asraa commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
eek sorry... probably shruthi thought it was ready since i had reviewed it open source or something

2024-10-18 14:23 UTC, asraa approved these changes
LGTM! Thank you for handling the CMake build, sorry about that.

2024-10-18 14:24 UTC, AlexanderViand-Intel commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
Eh, apart from not being squashed it was like 90% there anyway. I'll create a clean-up PR for the remaining 10% ;)

2024-10-18 15:27 UTC, code-perspective commented on lib/Dialect/Secret/Conversions/SecretToCGGI/CMakeLists.txt
Oops my bad for merging it! So sorry about that! will wait for that clean-up PR!

2024-10-18 15:33 UTC, AlexanderViand-Intel approved these changes

2024-10-19 00:32 UTC, merged