Cleanup deprecated applyPatternsAndFoldGreedily
google/heir pull request #1220
Opened 2024-12-21 09:23 UTC by ZenithalHourlyRate

Check https://github.com/llvm/llvm-project/pull/104649

2024-12-21 09:50 UTC, AlexanderViand-Intel requested changes
Can you do me a favor and add a TODO for #1221 on each change?

2024-12-21 09:50 UTC, AlexanderViand-Intel commented on lib/Dialect/CGGI/Transforms/ExpandLUT.cpp
> +    (void)applyPatternsGreedily(getOperation(), std::move(patterns));
something like this:
```suggestion
    // TODO (#1221): Investigate whether folding (default: on) can be skipped here.
    (void)applyPatternsGreedily(getOperation(), std::move(patterns));
```

2024-12-21 10:19 UTC, AlexanderViand-Intel approved these changes
Thanks! With the holidays, I'm not sure when this will be merged, though

2024-12-28 00:20 UTC, j2kun approved these changes

2024-12-30 17:19 UTC, merged