Abstract importer classes need an explicit virtual destructor
google/heir pull request #692
Opened 2024-05-23 16:39 UTC by raghav198

With Apple Clang 15.0.0, the implicitly generated destructors for `BooleanGateImporter`, `RTLILImporter`, and `LUTImporter` cause a run-time error when attempting to run any pipeline that uses them. Explicitly marking them virtual fixes this.

2024-05-23 16:52 UTC, j2kun requested changes
As I understand, the `virtual` keyword is only needed on the RTLILImporter base class, correct? Otherwise LGTM!

2024-05-24 14:36 UTC, j2kun approved these changes

2024-05-31 19:56 UTC, raghav198 commented
@j2kun I finally got the CLA stuff taken care of, is there anything else I need to do before it can be merged?

2024-05-31 20:05 UTC, j2kun commented
You're all good!

2024-06-03 14:25 UTC, asraa commented
Yep! From our end we make sure our internal presubmits and transformations work and then trigger the bot to submit it. (see https://heir.dev/docs/contributing/#internal-review-details) Just did :)

2024-06-03 14:28 UTC, merged