SecretnessAnalysis and ConvertIfToSelect fixes
google/heir pull request #889
Opened 2024-08-08 21:10 UTC by AlexanderViand-Intel

Fixes #839 by conservatively treating ops with regions (except control-flow ops, which the analysis framework handles directly) as "unknown" secretness (except if they have secret operands, in which case they're already "secret" anyway). See #888 for how this could be made a bit less conservative (not a high priority though, imho).

Investigating that issue also brought up some crashes in `ConvertIfToSelect`, because (a) it did not update the secretness of the operations it created and (b) it did not consider that a secretness could be absent or uninitialized. This PR fixes both issues. I guess this might also be an issue in the other data-oblivious transformations (@MeronZerihun can you please check that?)

Finally, this PR also adds a convenient (DEBUG-only) "printer" for the secretness analysis to `--convert-if-to-select`, which should make further fixes/improvements a bit easier. This works in the same way as the TargetSlot analysis, i.e., walking the IR and adding attributes. I wonder if there's a better place to put this debug logic, like maybe a debug-only pass that does nothing but run and the secretness analysis and augment the IR (@j2kun?)

2024-08-08 22:58 UTC, j2kun commented
> I wonder if there's a better place to put this debug logic, like maybe a debug-only pass that does nothing but run and the secretness analysis and augment the IR.

That sounds fair. I think there's probably a further step we could take, adding a util function like

```cpp
template <typename LatticeTy>
void attachLatticeAsAttribute(
    MLIRContext *context, 
    Operation *rootOp, 
    const std::string& attrName, 
    SomeCallbackType setAttr) {
  OpBuilder builder(context);
  rootOp->walk([&](Operation *op) {
    if (op->getNumResults() == 0) return;
    auto *lattice =
        solver.lookupState<LatticeTy>(op->getResult(0));
    if (!lattice) {
      op->setAttr(attrName, builder.getStringAttr("null"));
      return;
    }
    if (!lattice->getValue().isInitialized()) {
      op->setAttr(attrName, builder.getStringAttr("unknown"));
      return;
    }
    setAttr(op, lattice);
  });

  llvm::dbg() << "Op after attaching lattice attributes: " << *rootOp;
}
```

2024-08-08 23:06 UTC, j2kun approved these changes

2024-08-09 11:55 UTC, MeronZerihun requested changes
LGTM :)

2024-08-09 11:55 UTC, MeronZerihun commented on lib/Analysis/SecretnessAnalysis/SecretnessAnalysis.cpp
> +  // we appply the same conservative logic if any regions are detected
Not sure how this wasn't caught by the codespell check:
```suggestion
  // we apply the same conservative logic if any regions are detected
```

2024-08-09 12:16 UTC, MeronZerihun approved these changes

2024-08-09 12:16 UTC, MeronZerihun commented on lib/Analysis/SecretnessAnalysis/SecretnessAnalysis.cpp
```suggestion
// Propagate secretness for constants
```

2024-08-09 12:44 UTC, MeronZerihun commented
> This PR fixes both issues. I guess this might also be an issue in the other data-oblivious transformations (@MeronZerihun can you please check that?)

I think the other transformations will also have similar issues; I will make sure to replicate the fix and create a PR.

2024-08-09 14:56 UTC, asraa approved these changes
Thanks! I'll merge with the comment fixes

2024-08-09 17:25 UTC, AlexanderViand-Intel commented
> Thanks! I'll merge with the comment fixes

Fixes pushed & rebased

2024-08-09 21:25 UTC, merged