Design documentation for data-oblivious transformations
google/heir pull request #923
Opened 2024-08-20 13:12 UTC by MeronZerihun

Added design doc for data-oblivious transformation

2024-08-21 19:59 UTC, AlexanderViand-Intel reviewed
I know it's still a daft, but here's some suggestions on minimal changes to make to update it to the current state

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +func.func @my_function(%input : i1) -> () {
Given that the transformations now only apply to secret values, I think it's a good idea for the documentation to reflect that:
```suggestion
func.func @my_function(%input : i1 {secret.secret}) -> () {
```

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +func.func @my_function(%input : i16) -> (){
```suggestion
func.func @my_function(%input : i16 {secret.secret}) -> (){
```

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +- `scf.for`: Similar to affine.for operation, scf.for operation requires a body region that exactly contains one block that [terminates with `scf.yield`](https://mlir.llvm.org/docs/Dialects/SCFDialec
This is no longer accurate, as we now have a way to model this.

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +  // %MAX_INDEX is a constant that defines the maximum possible index value
code snippet should be updated to reflect the new attribute-based approach

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +- `scf.while`: This operation represents a generic while/do-while loop that keeps iterating as long as a condition is met. An input-dependent while condition introduces a data-dependent control flow
Probably a good point to reference https://github.com/google/heir/issues/922

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +Input-dependent memory access cause data-dependent memory footprints. A naive data-oblivious solution to this maybe doing read-write operations over the entire data structure while only performing th
remove the SIMD-friendly version, as we decided against implementing that (instead hoping that vectorization will be able to handle it)

2024-08-21 19:59 UTC, AlexanderViand-Intel commented on docs/content/en/docs/Design/do_transformation.md
> +- Access transformation: we currently don't support multi-dimensional tensors
```suggestion
```

2024-08-23 19:08 UTC, AlexanderViand-Intel approved these changes

2024-08-26 05:40 UTC, j2kun requested changes
Looks good! A few nits.

2024-08-26 05:40 UTC, j2kun commented on docs/content/en/docs/Design/do_transformation.md
> +<!-- mdformat on -->
```suggestion
---
title: Data-oblivious Transformations
weight: 9
---
```

Prompted by this PR, I have been tinkering with the auto-formatter in https://github.com/google/heir/pull/937. If you remove these html-style comments (as in that PR) then you should be able to run `mdformat --wrap=80` to get this PR to a consistent formatting style.

2024-08-26 05:40 UTC, j2kun commented on docs/content/en/docs/Design/do_transformation.md
> +A data-oblivious program is one that decouples data input from program execution. Such programs exhibit control-flow and memory access patterns that are independent of their input(s). This programmin
```suggestion
A data-oblivious program is one that decouples data input from program execution. Such programs exhibit control-flow and memory access patterns that are independent of their input(s). This programming model, when applied to encrypted data, is necessary for expressing FHE programs. There are 3 major transformations applied to convert a conventional program into a data-oblivious program:
```

2024-08-26 05:40 UTC, j2kun commented on docs/content/en/docs/Design/do_transformation.md
> +We implement a `ConvertIfToSelect` pass that transforms operations with secret-input conditions and with only Pure operations (i.e., operations that have no memory side effect and are speculatable) i
```suggestion
We implement a `ConvertIfToSelect` pass that transforms operations with secret-input conditions and with only Pure operations (i.e., operations that have no memory side effect and are speculatable) in their body. **This transformation cannot be applied to operations when side effects are present in only one of the two regions.** Although possible, we currently do not support transformations for operations where both regions have operations with matching side effects. When side effects are present, the pass fails.
```

2024-08-26 05:40 UTC, j2kun commented on docs/content/en/docs/Design/do_transformation.md
> +-->
```suggestion
```

Delete the comment

2024-08-26 05:40 UTC, j2kun commented on docs/content/en/docs/Design/do_transformation.md
> +- `scf.while`: This operation represents a generic while/do-while loop that keeps iterating as long as a condition is met. An input-dependent while condition introduces a data-dependent control flow
> We are working on adding early-exit support

Generally speaking it's best to leave "we will do" statements out of documentation. They often do not get completed (for better or worse) and it just becomes documentation rot. Or they get completed and the doc becomes stale as well. There's no shame in it, it's just better to state what the code does now as well as possible. Updating the docs to reflect the future will be a job for the people who implement those features.

Best would be to add a callout block like this near the start of the section

```
> [!NOTE]  
> Early exiting from loops is not supported in `scf` and `affine`, 
> so early exits are not supported in this pipeline.
> TODO(#922): support early exits
```

Then the TODO would be linked to this docs so people know to update it.

2024-08-26 19:39 UTC, j2kun commented
Now you should be able to rebase over main and run `pre-commit run --all-files` to apply the formatter automatically.

2024-10-09 05:03 UTC, AlexanderViand-Intel commented
@j2kun I've integrated your suggestions and rebased onto current main, should hopefully good to go now :)

2024-10-09 05:26 UTC, j2kun approved these changes

2024-10-09 07:21 UTC, merged