#822: Add check-heir CMake target that runs all tests
google/heir pull request #943
Opened 2024-08-26 20:32 UTC by ai-mannamalai

#822: Add check-heir CMake target that runs all tests
- Fixes #822
```bash
$ cmake -S . -B builddir -DENABLE_INSTALLED_MLIR=ON && cmake --build builddir 
$ cd builddir && make heir-check
```

2024-08-26 22:19 UTC, j2kun requested changes
Is this in a state to add to the CI workflow?

2024-08-26 22:19 UTC, j2kun commented on tests/CMakeLists.txt
> +add_custom_target(heir-check
for consistency with MLIR

```suggestion
add_custom_target(check-heir
```

2024-08-26 22:41 UTC, ai-mannamalai commented
Python code change is buggy as well:
```
FAIL: //tests/verilog:emit_verilog_memref_load.mlir.test (see /home/runner/.cache/bazel/_bazel_runner/0a8e1561e62ae8be6f076ff617869391/execroot/heir/bazel-out/k8-fastbuild/testlogs/tests/verilog/emit_verilog_memref_load.mlir.test/test.log)
INFO: From Testing //tests/verilog:emit_verilog_memref_load.mlir.test:
==================== Test output for //tests/verilog:emit_verilog_memref_load.mlir.test:
lit.py: /home/runner/.cache/bazel/_bazel_runner/0a8e1561e62ae8be6f076ff617869391/external/llvm-raw/llvm/utils/lit/lit/TestingConfig.py:153: fatal: unable to parse config file '/home/runner/.cache/bazel/_bazel_runner/0a8e1561e62ae8be6f076ff617869391/sandbox/linux-sandbox/3/execroot/heir/bazel-out/k8-fastbuild/bin/tests/verilog/emit_verilog_memref_load.mlir.test.runfiles/heir/tests/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/home/runner/.cache/bazel/_bazel_runner/0a8e1561e62ae8be6f076ff617869391/external/llvm-raw/llvm/utils/lit/lit/TestingConfig.py", line 141, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/home/runner/.cache/bazel/_bazel_runner/0a8e1561e62ae8be6f076ff617869391/sandbox/linux-sandbox/3/execroot/heir/bazel-out/k8-fastbuild/bin/tests/verilog/emit_verilog_memref_load.mlir.test.runfiles/heir/tests/lit.cfg.py", line 45, in <module>
    ":".join(str(runfiles_dir.joinpath(Path(path))) for path in tool_relpaths)
TypeError: can only concatenate str (not "NoneType") to str
```

2024-08-26 23:17 UTC, ai-mannamalai commented
> Is this in a state to add to the CI workflow?

No; CI workflow requires both LLVM build in CMake, enable Rust, enable Yosys etc. so quite some ways to go for CMake to be built on CI.

2024-08-26 23:30 UTC, j2kun commented
If possible, we should try to get something running, even if it omits e2e tests, just so it can get people to maintain the internal CMake lists files.

2024-08-27 01:40 UTC, ai-mannamalai commented
In my own development I’m compiling all pieces except the Yosys stuff and running some of selective tests (CGGI,) in lit. We could shoot for this in github CI builds; to get here we need additionally only the LLVM build in CMake. Alex Viand said he has some tips and tricks for this.

From: Jeremy Kun ***@***.***>
Date: Monday, August 26, 2024 at 4:30 PM
To: google/heir ***@***.***>
Cc: Muthu Annamalai ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [google/heir] #822: Add check-heir CMake target that runs all tests (PR #943)

If possible, we should try to get something running, even if it omits e2e tests, just so it can get people to maintain the internal CMake lists files. I'm all for incremental progress.

—
Reply to this email directly, view it on GitHub<https://github.com/google/heir/pull/943#issuecomment-2311285087>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APGLTDDMTB4VB75PQZGI6JLZTO3CHAVCNFSM6AAAAABNEXOJKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJRGI4DKMBYG4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-27 04:59 UTC, j2kun approved these changes

2024-08-27 13:28 UTC, asraa approved these changes

2024-08-27 13:34 UTC, merged

2024-09-08 10:08 UTC, AlexanderViand-Intel commented
> Alex Viand said he has some tips and tricks for this. 

I'm back to working on HEIR as of this week and will try to tackle the CMake stuff I promised ASAP :)

2024-09-09 01:21 UTC, ai-mannamalai commented
Awesome 🥳

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Alexander Viand ***@***.***>
Sent: Sunday, September 8, 2024 3:08:23 AM
To: google/heir ***@***.***>
Cc: Muthu Annamalai ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [google/heir] #822: Add check-heir CMake target that runs all tests (PR #943)


Alex Viand said he has some tips and tricks for this.

I'm back to working on HEIR as of this week and will try to tackle the CMake stuff I promised ASAP :)

—
Reply to this email directly, view it on GitHub<https://github.com/google/heir/pull/943#issuecomment-2336626105>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APGLTDBAVMWIWKCRHOWFVBDZVQOZPAVCNFSM6AAAAABNEXOJKCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZWGYZDMMJQGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>